services:
  - type: web
    name: tools
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /box
        destination: /gridfinity-box.html
      - type: rewrite
        source: /baseplate
        destination: /gridfinity-baseplate.html
      - type: rewrite
        source: /editor
        destination: /gridfinity-editor.html
      - type: rewrite
        source: /*
        destination: /index.html
